config/routes.rb
Rails.application.routes.draw do

  root 'atracaos#inicio'

  resources :atracaos, path: 'atracoes' do
    collection do
      get 'inicio'
      get 'explorar'
      get 'atracoes_do_usuario', defaults: {format: :js}
    end
    member do
      get 'marcar_assistida'
    end
  end
  resources :compartilhamentos do
    member do
      get 'marcar_compartilhada_assistida'
    end
  end

  devise_for :usuarios
  resources :usuarios

end

app/models/compartilhamento.rb
class Compartilhamento < ActiveRecord::Base

  belongs_to :usuario
  belongs_to :atracao
  has_many :compartilhamentos_usuarios, :class_name => 'CompartilhamentoUsuario', :foreign_key => :compartilhamento_id
  accepts_nested_attributes_for :compartilhamentos_usuarios, :allow_destroy => true
  has_and_belongs_to_many :usuarios_compartilhados, :class_name => 'Usuario'

  validates_presence_of :atracao_id, :usuario_id

  def compartilhado_com
    usuarios = ''
    self.usuarios_compartilhados.each_with_index do |usuario, index|
      usuarios += usuario.nome
      usuarios += ', ' if index < (self.usuarios_compartilhados.size - 1)
    end
    usuarios
  end
end

app/controllers/compartilhamentos_controller.rb
class CompartilhamentosController < ApplicationController
  before_action :authenticate_usuario!
  load_and_authorize_resource
  before_action :set_compartilhamento, only: [:show, :edit, :update, :destroy]
  before_action :busca_listas, only: [:new, :edit, :create, :update]

  respond_to :html

  def index
    @compartilhamentos = Compartilhamento.where(:usuario_id => current_user.id)
    @compartilhamentos_comigo = current_usuario.compartilhamentos_recebidos
    respond_with(@compartilhamentos)
  end

  def show
    respond_with(@compartilhamento)
  end

  def busca_listas
    @atracoes = Atracao.where(:usuario_id => current_user.id)
    @usuarios = Usuario.where.not(:id => current_user.id)
  end

  def new
    @compartilhamento = Compartilhamento.new
    @compartilhamento.atracao_id = params[:atracao_id] if params[:atracao_id]
    @compartilhamento.compartilhamentos_usuarios.build
    respond_with(@compartilhamento)
  end

  def edit
  end

  def create
    @compartilhamento = Compartilhamento.new(compartilhamento_params)
    @compartilhamento.usuario_id = current_user.id
    @compartilhamento.save
    respond_with(@compartilhamento)
  end

  def update
    @compartilhamento.update(compartilhamento_params)
    respond_with(@compartilhamento)
  end

  def destroy
    @compartilhamento.destroy
    respond_with(@compartilhamento)
  end

  def marcar_compartilhada_assistida
    @compartilhamento.compartilhamentos_usuarios.find_by(:usuario_id => current_usuario.id).update(:assistida => true)
    redirect_to root_path
  end

  private
  def set_compartilhamento
    @compartilhamento = Compartilhamento.find(params[:id])
  end

  def compartilhamento_params
    params.require(:compartilhamento).permit(:usuario_id, :atracao_id, :comentario, :compartilhamentos_usuarios_attributes => [:id, :usuario_id, :_destroy])
  end
end

app/helpers/compartilhamentos_helper.rb
module CompartilhamentosHelper
end

app/views/compartilhamentos/_form.html.erb
<%= nested_form_for(@compartilhamento, :html => {:class => "form-horizontal", :role => "form"}) do |f| %>
    <% if @compartilhamento.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@compartilhamento.errors.count, "error") %> proibiram este compartilhamento de ser
            salvo:</h4>

          <ul>
            <% @compartilhamento.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :atracao_id, 'Atração', :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select :atracao_id, @atracoes, :id, :nome, {:prompt => 'Escolha uma atração'}, {:class => "form-control chosen-select", :style => 'width: 200px;'} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :pessoas, 'Pessoas', :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <div class="panel panel-info">
          <div class="panel-heading">
            Compartilhar com
            <div class="actions" style="display: inline-block; float: right;">
              <%= f.link_to_add "<i class='glyphicon glyphicon-plus'></i> Adicionar outra pessoa".html_safe, :compartilhamentos_usuarios, :data => {:target => "#pessoas"}, :class => 'btn btn-default btn-xs' %>
            </div>
          </div>
          <table class="table table-striped table-bordered">
            <tbody id="pessoas">
            <%= f.fields_for :compartilhamentos_usuarios, :wrapper => false do |c| %>
                <tr class="fields">
                  <td><%= c.collection_select :usuario_id, @usuarios, :id, :nome, {:prompt => 'Escolha uma pessoa'}, {:class => "form-control"} %></td>
                  <td width="1%" style="text-align: center;">
                    <%= c.link_to_remove :class => 'btn btn-danger' do %>
                        <i class='glyphicon glyphicon-trash'></i>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :comentario, 'Comentário', :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :comentario, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Salvar', :class => "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/compartilhamentos/edit.html.erb
<div class="page-header">
  <%= link_to compartilhamentos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @compartilhamento, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editar compartilhamento</h1>
</div>

<%= render 'form' %>

app/views/compartilhamentos/index.html.erb
<div class="page-header">
  <%= link_to new_compartilhamento_path, :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      Novo Compartilhamento
  <% end %>
  <h1>Meus compartilhamentos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>

      <th>Compartilhado Com</th>

      <th>Comentario</th>

      <th width="1%">Mostrar</th>
      <th width="1%">Editar</th>
      <th width="1%">Apagar</th>
    </tr>
    </thead>

    <tbody>
    <%= content_tag_for(:tr, @compartilhamentos) do |compartilhamento| %>

        <td><%= compartilhamento.compartilhado_com %></td>

        <td><%= compartilhamento.comentario %></td>

        <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-search'></i>".html_safe, compartilhamento, :class => 'btn btn-info btn-sm' %></td>
        <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_compartilhamento_path(compartilhamento), :class => 'btn btn-warning btn-sm' %></td>
        <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, compartilhamento, method: :delete, data: {confirm: 'Você tem certeza?'}, :class => 'btn btn-danger btn-sm' %></td>
    <% end %>
    </tbody>
  </table>
</div>

<div class="page-header">
  <h1>Atrações compartilhadas comigo</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Atração</th>
      <th>Compartilhado por</th>
      <th>Comentário</th>
      <th>Já Assistiu?</th>
    </tr>
    </thead>
    <tbody>
    <%= content_tag_for(:tr, @compartilhamentos_comigo) do |compartilhamento| %>
        <td><%= compartilhamento.atracao.nome %></td>
        <td><%= compartilhamento.usuario.nome %></td>
        <td><%= compartilhamento.comentario %></td>
        <td><%= compartilhamento.compartilhamentos_usuarios.find_by(:usuario_id => current_usuario.id).assistida? %></td>
    <% end %>
    </tbody>
  </table>
</div>

app/views/compartilhamentos/new.html.erb
<div class="page-header">
  <%= link_to compartilhamentos_path, :class => 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Voltar
  <% end %>
  <h1>Novo compartilhamento</h1>
</div>

<%= render 'form' %>

app/views/compartilhamentos/show.html.erb
<div class="page-header">
  <%= link_to compartilhamentos_path, :class => 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Voltar
  <% end %>
  <%= link_to edit_compartilhamento_path(@compartilhamento), :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Editar
  <% end %>
  <h1>Mostrar compartilhamento</h1>
</div>

<dl class="dl-horizontal">

  <dt>Compartilhado com:</dt>
  <dd><%= @compartilhamento.compartilhado_com %></dd>


  <dt>Comentario:</dt>
  <dd><%= @compartilhamento.comentario %></dd>


</dl>