config/routes.rb
Rails.application.routes.draw do

  root 'atracaos#inicio'

  resources :atracaos, path: 'atracoes' do
    collection do
      get 'inicio'
      get 'explorar'
      get 'atracoes_do_usuario', defaults: {format: :js}
    end
    member do
      get 'marcar_assistida'
    end
  end
  resources :compartilhamentos do
    member do
      get 'marcar_compartilhada_assistida'
    end
  end

  devise_for :usuarios
  resources :usuarios

end

app/models/atracao.rb
class Atracao < ActiveRecord::Base

  self.table_name = 'atracoes'

  TIPO_FILME = {:tipo => 1, :label => 'Filme'}
  TIPO_PROGRAMA_TV = {:tipo => 2, :label => 'Programa de TV'}
  TIPO_SERIE = {:tipo => 3, :label => 'Série'}
  TIPOS = [TIPO_FILME, TIPO_PROGRAMA_TV, TIPO_SERIE]

  belongs_to :usuario
  has_many :compartilhamentos, :through => :atracoes_compartilhadas

  validates_presence_of :usuario_id, :nome, :midia, :tipo
  validate :formato_exibicao

  def exibicao_dt_picker
    if self.exibicao.present?
      self.exibicao.strftime("%d/%m/%Y %H:%M")
    end
  end

  def assistida?
    if self.assistida
      'Sim'
    else
      'Não'
    end
  end

  private

  def formato_exibicao
    if self.exibicao.present?
      self.errors.add(:exibicao, 'não está em um formato válido, use o seletor...') unless DateTime.parse(self.exibicao.to_s)
    end
  end

end

app/controllers/atracaos_controller.rb
class AtracaosController < ApplicationController
  before_action :authenticate_usuario!
  load_and_authorize_resource
  before_action :set_atracao, only: [:show, :edit, :update, :destroy, :marcar_assistida]

  respond_to :html

  def inicio
    @atracaos = Atracao.where(:usuario_id => current_user.id, :assistida => false).order(:exibicao)
    @compartilhamentos = current_usuario.compartilhamentos_recebidos.where('compartilhamentos_usuarios.assistida is false')
  end

  def index
    @atracaos = Atracao.where(:usuario_id => current_user.id).order(:assistida, :exibicao)
    respond_with(@atracaos)
  end

  def show
    respond_with(@atracao)
  end

  def new
    @atracao = Atracao.new
    respond_with(@atracao)
  end

  def edit
  end

  def create
    @atracao = Atracao.new(atracao_params)
    @atracao.usuario_id = current_user.id
    respond_to do |format|
      if @atracao.save
        flash[:notice] = "Atração #{@atracao.nome} criada com sucesso."
        format.html { redirect_to(root_path) }
        format.xml { render xml: @atracao }
      else
        format.html { render action: "new" }
        format.xml { render xml: @atracao }
      end
    end
  end

  def update
    @atracao.update(atracao_params)
    respond_with(@atracao)
  end

  def destroy
    @atracao.destroy
    respond_with(@atracao)
  end

  def explorar
    @usuarios = Usuario.where.not(:id => current_user.id)
  end

  def atracoes_do_usuario
    @usuario = Usuario.find(params[:usuario_id])
    @atracoes = @usuario.atracaos
  end

  def marcar_assistida
    @atracao.update(:assistida => true)
    redirect_to root_path
  end

  private
  def set_atracao
    @atracao = Atracao.find(params[:id])
  end

  def atracao_params
    params.require(:atracao).permit(:nome, :midia, :exibicao, :tipo)
  end
end

app/helpers/atracaos_helper.rb
module AtracaosHelper
end

app/views/atracaos/_atracoes.html.erb
<div class="panel-body">
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
      <tr>
        <th>Atração</th>
      </tr>
      </thead>

      <tbody>
      <% @atracoes.each do |atracao| %>
          <tr>
            <td><%= atracao.nome %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/atracaos/_form.html.erb
<%= form_for(@atracao, :html => {:class => "form-horizontal", :role => "form"}) do |f| %>
    <% if @atracao.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
          <h4><%= pluralize(@atracao.errors.count, "error") %> proibiram esta atração de ser salva:</h4>

          <ul>
            <% @atracao.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group required">
          <%= f.label :nome, :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :nome, :class => "form-control" %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group required">
          <%= f.label :tipo, :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.select :tipo, options_for_select(Atracao::TIPOS.collect { |t| [t[:label], t[:tipo]] }), {:include_blank => 'Escolha um tipo...'}, {:class => 'form-control'} %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group required">
          <%= f.label :midia, :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :midia, :class => "form-control" %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :exibicao, :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <div class="input-group date" id="datetimepicker1">
              <%= f.text_field :exibicao, :class => "dt_picker form-control", :value => @atracao.exibicao_dt_picker %>
              <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                    </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-11">
        <%= f.submit 'Salvar', :class => "btn btn-primary" %>
      </div>
    </div>
<% end %>

<script>
    $(function () {
        $('.dt_picker').datetimepicker({
            format: 'DD/MM/YYYY HH:mm',
            sideBySide: true,
            minuteStepping: 15
        });
    });
</script>

app/views/atracaos/atracoes_do_usuario.js.erb
var elemento = $('#us_<%= @usuario.id %>');
$(elemento).find('.panel-body').remove();
$(elemento).append('<%= j render 'atracoes' %>');

app/views/atracaos/edit.html.erb
<div class="page-header">
  <%= link_to atracaos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @atracao, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editar atração</h1>
</div>

<%= render 'form' %>

app/views/atracaos/explorar.html.erb
<div class="page-header">
  <h1>Descobrindo o gosto da galera!</h1>
</div>

<% @usuarios.each_with_index do |usuario, index| %>
    <div id="us_<%= usuario.id %>" class="panel panel-default">
      <div class="panel-heading">
        <b><%= usuario.nome %></b>

        <div class="actions" style="display: inline-block; float: right;">
          <%= link_to "<i class='glyphicon glyphicon-search'></i> Minhas atrações".html_safe, atracoes_do_usuario_atracaos_path(:usuario_id => usuario.id), :remote => true, :class => 'btn btn-default btn-xs' %>
        </div>
      </div>
    </div>
<% end %>

app/views/atracaos/index.html.erb
<div class="page-header">
  <%= link_to new_atracao_path, :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      Cadastrar Atração
  <% end %>
  <%= link_to explorar_atracaos_path, :class => 'btn btn-info' do %>
      <span class="glyphicon glyphicon-search"></span>
      Visualizar Atrações da Galera
  <% end %>
  <h1>Minhas atrações</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>

      <th>Nome</th>

      <th>Midia</th>

      <th>Exibicao</th>

      <th style="width: 100px;">Já assistiu?</th>
      <th width="1%">Compartilhar</th>
      <th width="1%">Editar</th>
      <th width="1%">Apagar</th>
    </tr>
    </thead>

    <tbody>
    <% @atracaos.each do |atracao, index| %>
        <tr>
          <td><%= atracao.nome %></td>

          <td><%= atracao.midia %></td>

          <td><%= l atracao.exibicao if atracao.exibicao %></td>

          <td style="text-align: center;">
            <%= atracao.assistida? %>
          </td>

          <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-user'></i>".html_safe, new_compartilhamento_path(:atracao_id => atracao.id), :class => 'btn btn-info btn-sm' %></td>
          <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_atracao_path(atracao), :class => 'btn btn-warning btn-sm' %></td>
          <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, atracao, method: :delete, data: {confirm: 'Você tem certeza?'}, :class => 'btn btn-danger btn-sm' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/atracaos/inicio.html.erb
<div class="page-header">
  <%= link_to new_atracao_path, :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      Cadastrar Atração
  <% end %>
  <%= link_to explorar_atracaos_path, :class => 'btn btn-info' do %>
      <span class="glyphicon glyphicon-search"></span>
      Visualizar Atrações da Galera
  <% end %>
  <h1>Próximas atrações</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>

      <th>Nome</th>

      <th>Midia</th>

      <th>Exibicao</th>

      <th style="width: 100px;">Já assistiu?</th>
      <th width="1%">Compartilhar</th>
      <th width="1%">Editar</th>
      <th width="1%">Apagar</th>
    </tr>
    </thead>

    <tbody>
    <% @atracaos.each do |atracao, index| %>
        <tr>
          <td><%= atracao.nome %></td>

          <td><%= atracao.midia %></td>

          <td><%= l atracao.exibicao if atracao.exibicao %></td>

          <td style="text-align: center;">
            <%= link_to "<i class='glyphicon glyphicon-ok'></i>".html_safe, marcar_assistida_atracao_path(atracao), :class => 'btn btn-success btn-sm' %>
          </td>

          <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-user'></i>".html_safe, new_compartilhamento_path(:atracao_id => atracao.id), :class => 'btn btn-info btn-sm' %></td>
          <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_atracao_path(atracao), :class => 'btn btn-warning btn-sm' %></td>
          <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, atracao, method: :delete, data: {confirm: 'Você tem certeza?'}, :class => 'btn btn-danger btn-sm' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="page-header">
  <h1>Compartilhadas comigo</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Atração</th>
      <th>Compartilhado por</th>
      <th>Comentário</th>
      <th style="width: 100px;">Já assistiu?</th>
    </tr>
    </thead>
    <tbody>
    <%= content_tag_for(:tr, @compartilhamentos) do |compartilhamento| %>
        <td><%= compartilhamento.atracao.nome %></td>
        <td><%= compartilhamento.usuario.nome %></td>
        <td><%= compartilhamento.comentario %></td>
        <td style="text-align: center;">
          <%= link_to "<i class='glyphicon glyphicon-ok'></i>".html_safe, marcar_compartilhada_assistida_compartilhamento_path(compartilhamento), :class => 'btn btn-success btn-sm' %>
        </td>
    <% end %>
    </tbody>
  </table>
</div>

app/views/atracaos/new.html.erb
<div class="page-header">
  <%= link_to atracaos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Cadastrar atração</h1>
</div>

<%= render 'form' %>

app/views/atracaos/show.html.erb
<div class="page-header">
  <%= link_to atracaos_path, :class => 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Voltar
  <% end %>
  <%= link_to edit_atracao_path(@atracao), :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Editar
  <% end %>
  <h1>Mostrar atração</h1>
</div>

<dl class="dl-horizontal">

  <dt>Usuario:</dt>
  <dd><%= @atracao.usuario.nome %></dd>


  <dt>Nome:</dt>
  <dd><%= @atracao.nome %></dd>


  <dt>Midia:</dt>
  <dd><%= @atracao.midia %></dd>


  <dt>Exibicao:</dt>
  <dd><%= l @atracao.exibicao if @atracao.exibicao %></dd>


</dl>