config/routes.rb
Rails.application.routes.draw do

  root 'atracaos#inicio'

  resources :atracaos, path: 'atracoes' do
    collection do
      get 'inicio'
      get 'explorar'
      get 'atracoes_do_usuario', defaults: {format: :js}
    end
    member do
      get 'marcar_assistida'
    end
  end
  resources :compartilhamentos do
    member do
      get 'marcar_compartilhada_assistida'
    end
  end

  devise_for :usuarios
  resources :usuarios

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :atracaos
  has_many :compartilhamentos
  has_many :compartilhamentos_usuarios, :class_name => 'CompartilhamentoUsuario', :foreign_key => :compartilhamento_id
  has_and_belongs_to_many :compartilhamentos_recebidos, class_name: 'Compartilhamento'

  validates_presence_of :nome

  before_save :setar_admin, if: :sem_usuarios?

  def admin_to_s
    valor = self.admin
    if valor
      'Sim'
    else
      'Não'
    end
  end

  private
  def sem_usuarios?
    Usuario.all.empty?
  end

  def setar_admin
    self.admin = true
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :authenticate_usuario!
  load_and_authorize_resource
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_usuario
    @usuario = Usuario.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def usuario_params
    params.require(:usuario).permit(:nome, :admin)
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario, :html => {:class => "form-horizontal", :role => "form"}) do |f| %>
    <% if @usuario.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@usuario.errors.count, "error") %> proibiram este usuario de ser salvo:</h4>

          <ul>
            <% @usuario.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-group">
      <%= f.label :nome, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :nome, :class => "form-control" %>
      </div>
    </div>

    <% unless @usuario.id == current_usuario.id %>
        <div class="form-group">
          <%= f.label :admin, :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.check_box :admin %>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Salvar', :class => "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/usuarios/edit.html.erb
<div class="page-header">
  <%= link_to usuarios_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @usuario, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editar usuario</h1>
</div>

<%= render 'form' %>

app/views/usuarios/index.html.erb
<div class="page-header">
  <h1>Listando usuários</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Nome</th>
      <th width="1%">Administrador</th>
      <th width="1%">Mostrar</th>
      <th width="1%">Editar</th>
    </tr>
    </thead>

    <tbody>
    <%= content_tag_for(:tr, @usuarios) do |usuario| %>
        <td><%= usuario.nome %></td>
        <td style="text-align: center;"><%= usuario.admin_to_s %></td>
        <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-search'></i>".html_safe, usuario, :class => 'btn btn-info btn-sm' %></td>
        <td style="text-align: center;"><%= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_usuario_path(usuario), :class => 'btn btn-warning btn-sm' %></td>
    <% end %>
    </tbody>
  </table>
</div>

app/views/usuarios/new.html.erb
<div class="page-header">
  <%= link_to usuarios_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Cadastrar usuario</h1>
</div>

<%= render 'form' %>

app/views/usuarios/show.html.erb
<div class="page-header">
  <%= link_to usuarios_path, :class => 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Voltar
  <% end %>
  <%= link_to edit_usuario_path(@usuario), :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Editar
  <% end %>
  <h1>Mostrar usuario</h1>
</div>

<dl class="dl-horizontal">

  <dt>Nome:</dt>
  <dd><%= @usuario.nome %></dd>

  <dt>Administrador:</dt>
  <dd><%= @usuario.admin_to_s %></dd>


</dl>