config/routes.rb
Rails.application.routes.draw do

  root 'atracaos#inicio'

  resources :atracaos, path: 'atracoes' do
    collection do
      get 'inicio'
      get 'explorar'
      get 'atracoes_do_usuario', defaults: {format: :js}
    end
    member do
      get 'marcar_assistida'
    end
  end
  resources :compartilhamentos do
    member do
      get 'marcar_compartilhada_assistida'
    end
  end

  devise_for :usuarios
  resources :usuarios

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>FilsepTV - Organizador de Atrações</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "FilsepTV", root_path, :class => "navbar-brand" %>
    </div>
    <% if usuario_signed_in? %>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= (controller_name == 'atracaos' and action_name == 'inicio') ? 'active' : '' %>"><%= link_to 'Início', root_path %></li>
            <% if can? :manage, Usuario %>
                <li class="<%= controller_name == 'usuarios' ? 'active' : '' %>"><%= link_to 'Usuários', usuarios_path %></li>
            <% end %>
            <li class="<%= (controller_name == 'atracaos' and action_name != 'inicio') ? 'active' : '' %>"><%= link_to 'Atrações', atracaos_path %></li>
            <li class="<%= controller_name == 'compartilhamentos' ? 'active' : '' %>"><%= link_to 'Compartilhamentos', compartilhamentos_path %></li>
          </ul>
          <% if usuario_signed_in? %>
              <div style="display: inline-block; float: right; padding-top: 15px; padding-bottom: 15px; color: #dadada;">
                Logado como
                <b><%= current_usuario.nome %></b>, <%= link_to "Deslogar? <i class='glyphicon glyphicon-log-out'></i>".html_safe, destroy_usuario_session_path, :method => :delete, :style => 'color: #fff; font-weight: bold;' %>
              </div>
          <% end %>
        </div>
    <% end %>
  </div>
</nav>
<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
      <% end %>
  <% end %>

  <%= yield %>
</div>
</body>
</html>